"""chenged to open_meteo data

Revision ID: 0c1b31e4a006
Revises: 12c596a06a46
Create Date: 2024-05-07 17:52:32.696931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c1b31e4a006'
down_revision: Union[str, None] = '12c596a06a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meteo_data', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('precipitation', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('dew_point', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('soil_temperature_0cm', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('soil_temperature_6cm', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('soil_temperature_18cm', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('soil_moisture_0_to_1cm', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('soil_moisture_1_to_3cm', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('soil_moisture_3_to_9cm', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('soil_moisture_9_to_27cm', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('temperature_max', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('temperature_min', sa.Float(), nullable=True))
    op.add_column('meteo_data', sa.Column('precipitation_sum', sa.Float(), nullable=True))
    op.alter_column('meteo_data', 'humidity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('meteo_data', 'wind_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('meteo_data', 'sunrise',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('meteo_data', 'sunset',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('meteo_data', 'temp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meteo_data', sa.Column('temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('meteo_data', 'sunset',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('meteo_data', 'sunrise',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('meteo_data', 'wind_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('meteo_data', 'humidity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('meteo_data', 'precipitation_sum')
    op.drop_column('meteo_data', 'temperature_min')
    op.drop_column('meteo_data', 'temperature_max')
    op.drop_column('meteo_data', 'soil_moisture_9_to_27cm')
    op.drop_column('meteo_data', 'soil_moisture_3_to_9cm')
    op.drop_column('meteo_data', 'soil_moisture_1_to_3cm')
    op.drop_column('meteo_data', 'soil_moisture_0_to_1cm')
    op.drop_column('meteo_data', 'soil_temperature_18cm')
    op.drop_column('meteo_data', 'soil_temperature_6cm')
    op.drop_column('meteo_data', 'soil_temperature_0cm')
    op.drop_column('meteo_data', 'dew_point')
    op.drop_column('meteo_data', 'precipitation')
    op.drop_column('meteo_data', 'temperature')
    # ### end Alembic commands ###
