"""deleted day

Revision ID: 12c596a06a46
Revises: 16670270ff97
Create Date: 2024-05-07 03:00:09.409950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c596a06a46'
down_revision: Union[str, None] = '16670270ff97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meteo_data', 'day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meteo_data', sa.Column('day', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
